version: '3.8'

services:
  postgres:
    image: postgres:14.1
    restart: unless-stopped
    container_name: classXDB
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - bull

  cache:
    image: redis:7.0.0
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - bull

  bullx:
    build:
      context: backgroundJobs
      dockerfile: Dockerfile
    networks:
      - bull
    env_file:
      - .env


volumes:
  postgres:
  cache:

networks:
  bull: